name: testing inputs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      app_name:
        default: helloworld
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: sending default app-name
      run: echo "my application name is ${{ inputs.app_name }}"
