name: testing inputs for gha
on:
  push:
    branches:
      - main
    inputs:
      app_name:
        default: helloworld
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: sending default app-name
      run: echo "my application name is ${{ github.events.inputs.app_name }}"
