name: testing inputs for gha
on:
  push:
    branches:
      - main
    inputs:
      app_name:
        default: helloworld
env:
  app_name: Hellow-World
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: sending default app-name
      run: echo "my application name is ${{ env.app_name }}"
